### ISSUE TITLE
UI issue with inline tags

### ISSUE THREAD

**Issue by Codemaine** [JaleelB/emblor#40]
I saw you recently implemented the inline tags, and when I tried to implement it in my app, I got this styling issue.
<img width="498" alt="image" src="https://github.com/JaleelB/emblor/assets/64845752/a941ee70-59ad-4c19-b296-9cd4fdef75bb">

**Comment by JaleelB** [comment]
Firstly, make sure you update to version 1.1.1 of the package. Version 1.1.1 corrected a styling issue I noticed. Check your package.json file to check the version of the package

**Comment by Codemaine** [comment]
Yea, I've confirmed it's on version 1.1.1

<img width="180" alt="image" src="https://github.com/JaleelB/emblor/assets/64845752/e8251d58-9c68-48b0-9e3f-3f511350000a">

**Comment by JaleelB** [comment]
> Yea, I've confirmed it's on version 1.1.1
> 
> <img alt="image" width="180" src="https://private-user-images.githubusercontent.com/64845752/333801159-e8251d58-9c68-48b0-9e3f-3f511350000a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDI1MzUsIm5iZiI6MTcxNjY0MjIzNSwicGF0aCI6Ii82NDg0NTc1Mi8zMzM4MDExNTktZTgyNTFkNTgtOWM2OC00OGIwLTllM2YtM2Y1MTEzNTAwMDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzMDM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhOTNiMWEwYTQyMDMwMDhhNTY3NWViOWM0NGQ1OTY3ZDc3NTk2NjJmYmUwZjRkMDEwMjdmYWE2N2M1OTE1ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VLAUTOHUb_GFSia38BzPa-Y5JbfyoM2lSzrR6Pbe9wk">

OK. Send a reproduction of this error so I can better understand the context of your issue. I tried reproducing it but all instances I created have the correct styling implementation. Preferably a code sandbox or a hosted link so I can observe the dom

**Comment by Codemaine** [comment]
It's being used in a big project. Should I share how I used the component and our tailwindcss config file?

**Comment by JaleelB** [comment]
> It's being used in a big project. Should I share how I used the component and our tailwindcss config file?

@Codemaine That would be helpful, so yes. I would still like you to recreate the environment outside your project to narrow down whether or not this issue was caused by something in your project. For this you can just create a simple Next.js app in a code sandbox, follow the shadcn setup guide, install and setup the package, then share the link

**Comment by Codemaine** [comment]
Sure. Here's the codesandbox link: https://codesandbox.io/p/devbox/mystifying-khorana-hhc69f?workspaceId=be20086d-945c-402b-ae8c-2b40ca5f7c9a

**Comment by JaleelB** [comment]
> Sure. Here's the codesandbox link: https://codesandbox.io/p/devbox/mystifying-khorana-hhc69f?workspaceId=be20086d-945c-402b-ae8c-2b40ca5f7c9a

You aren't using the shadcn css variables in the environment. Make sure you're also using them in your project

**Comment by Codemaine** [comment]
I can confirm that I'm using the shadcn css variables in my project.

<img width="178" alt="image" src="https://github.com/JaleelB/emblor/assets/64845752/3e1b6783-aa8a-4628-988f-333a08bc75dd">

**Comment by JaleelB** [comment]
> I can confirm that I'm using the shadcn css variables in my project.
> 
> <img alt="image" width="178" src="https://private-user-images.githubusercontent.com/64845752/333879060-3e1b6783-aa8a-4628-988f-333a08bc75dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mzk5OTMsIm5iZiI6MTcxNjczOTY5MywicGF0aCI6Ii82NDg0NTc1Mi8zMzM4NzkwNjAtM2UxYjY3ODMtYWE4YS00NjI4LTk4OGYtMzMzYTA4YmM3NWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE2MDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiM2I0YTY5NDI1ZWZjMTI1YWYxYTM2ZDYzYzIyODFkZjBmM2E4OTRmOTE3NGFhNWMzOTQ1MjViYjg4ODRiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Su7KIk0rWBwYcEoSrS60tN9x_ZbyU68-zBEmRz1rZs">

@Codemaine Based on your first image, i think i know what the issue is. Do you have a live version of your app using the package? I dont think the min-width and height I included in the fix are being applied to the input in your use case. From what I can see the input is taking on the full width of the container. This is how it should be

<img width="605" alt="Screenshot 2024-05-26 at 12 14 49 PM" src="https://github.com/JaleelB/emblor/assets/78449846/b05ee8c6-00d8-4e5a-a67f-64fcd74c07eb">

**Comment by Codemaine** [comment]
Alright, here's the link: https://zest-git-inventory-zest-africa.vercel.app/products. It's the category field on the top. I'd delete this comment in 20 minutes as the project is confidential.

**Comment by JaleelB** [comment]
@Codemaine Thanks. You can delete the comment now. I figured out what the issue is. Ypu are applying this min-width of 450px, which overrides the min-width that is set internally. That along with the w-full class causes the input to always be the size of the container so the tags are stacked above it. Remove that min-width and you should be fine.  I see you also applying a shadow. If you just want the input to show without that outline also, just do shadow none

<img width="394" alt="Screenshot 2024-05-26 at 1 38 48 PM" src="https://github.com/JaleelB/emblor/assets/78449846/1b0ecb95-00e6-4352-91a2-73f1738ff75f">

**Comment by JaleelB** [comment]
@Codemaine I deleted the comment for you. Just follow what I said and you should be fine. Once that works, just close the issue as done

**Comment by Codemaine** [comment]
The min-width was from the demo on the landing page lmao. I removed the min-width and w-full classes, yet i'm still getting the styling issue.

**Comment by JaleelB** [comment]
> The min-width was from the demo on the landing page lmao. I removed the min-width and w-full classes, yet i'm still getting the styling issue.

@Codemaine What exactly is the styling issue you're referring to then? I removed the "sm:min-w-[450px]" class from the input you showed and that solved the input not being inline. Is that not what you were referring to?

**Comment by JaleelB** [comment]
Also, update to the latest version of the package

**Comment by Codemaine** [comment]
Oh my bad. I thought the inline tags showed horizontally in the input field.
