### ISSUE TITLE
Autocomplete suggestions aren't clickable and don't always appear

### ISSUE THREAD

**Issue by mfigdore** [JaleelB/emblor#61]
I'm running into the same issue as #19, where autocomplete suggestions aren't clickable. The solution in that issue didn't work for me.

Additionally, I don't see any autocomplete suggestions when the name of a tag is partially typed, but then the autocomplete panel is opened.

![image](https://github.com/JaleelB/emblor/assets/31799118/ddac39b0-93b0-4cd9-bce3-af2d836d9bab)

Thanks for the great repo and the help :)

**Comment by JaleelB** [comment]
Hey @mfigdore 

Thank you for reporting this and for your kind words about the repo! To better assist you, could you please provide a few more details:

Version Information: Could you confirm the version of the package you are currently using? This will help us understand if you have the latest updates where the issue was addressed.

Code Snippet: Could you share a snippet of how you're implementing the autocomplete feature in your setup? This will help us identify any potential misconfigurations or specific use cases.

Browser and Environment: Which browser and version are you using? Also, are you seeing this behavior in a specific environment (e.g., development, production)?

Error Logs: Are there any console errors when you attempt to use the autocomplete feature or when the issue occurs?

Any additional information or screenshots you could provide would be greatly helpful in diagnosing the problem more accurately.

Thanks for your cooperation!

**Comment by mfigdore** [comment]
I found the issue with the autocomplete suggestions not being clickable — this is because I’m using Emblor within a shadcn Dialog. 
It looks like [this](https://github.com/shadcn-ui/ui/issues/1511#issuecomment-1810682366) could be the solution. Is it possible to add a property to the API to set `modal={true}`?

Regarding autocomplete suggestions not appearing, this happens in Emblor 1.4.0 and can be demoed using the autocomplete [example](https://github.com/shadcn-ui/ui/issues/1511#issuecomment-1810682366) on the website:
1. Remove a tag
2. Type the first 4 letters of the tag
3. Press the arrow to open the autocomplete menu

**Comment by JaleelB** [comment]
@mfigdore 

The enhancements discussed in this thread have been addressed in the [v1.4.2 release](https://github.com/JaleelB/emblor/releases/tag/emblor%401.4.2).
