### ISSUE TITLE
Copy/Paste to create multiple tags at ones

### ISSUE THREAD

**Issue by kittenkill** [JaleelB/emblor#73]
### Feature description

Hello ✌🏽,

I was wondering if its possible to copy/paste a bunch of strings, comma sepatated, and make emblor create multiple tags, instead of just 1.

Do you think this can be made somehow?

Thanks!

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by JaleelB** [comment]
@kittenkill 

The enhancements discussed in this thread have been addressed in the [v1.4.3 release](https://github.com/JaleelB/emblor/releases/tag/emblor%401.4.3).

**Comment by JaleelB** [comment]
> @kittenkill
> 
> The enhancements discussed in this thread have been addressed in the [v1.4.3 release](https://github.com/JaleelB/emblor/releases/tag/emblor%401.4.3).

Give it a moment. It seems the publish to npm failed

**Comment by JaleelB** [comment]
> Hi @JaleelB
> 
> Awesome feedback!
> 
> Not sure if im doing something wrong tho. I had to add this:
> 
> ```js
> autocompleteOptions={[]}
> ```
> 
> Else, it will fail [here](https://github.com/JaleelB/emblor/blob/main/packages/emblor/src/tag/tag-input.tsx#L346) With
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'filter')
> ```
> 
> After that, however, could not see the new functionality working. Is it enabled by default for , as a separator? Should it be seenable on [emblor.jaleelbennett.com](https://emblor.jaleelbennett.com/)?

An error was introduced in v1.4.2 hence why you had to initialize the autocompleteOptions with an empty array. This issue has been addressed in the [v1.4.4 release](https://github.com/JaleelB/emblor/releases/tag/emblor%401.4.4).

In order to use the copy-paste functionality, you have to pass the `addOnPaste` prop. There is the demo and details for this prop on the [Api reference](https://emblor.jaleelbennett.com/api-reference) page
